var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/admin/crm/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t5lowh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0w8fg-2.js")
R.c("server/chunks/ssr/_02cyj8l._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04t03qg._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fw3mdu._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0r5yz5t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_dashboard_loading_tsx_18gtejz._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_admin_crm_page_actions_0v0svm2.js")
R.m(40454)
module.exports=R.m(40454).exports
