// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard/admin" | "/dashboard/admin/attendance" | "/dashboard/admin/batches" | "/dashboard/admin/colleges" | "/dashboard/admin/courses" | "/dashboard/admin/crm" | "/dashboard/admin/finance" | "/dashboard/admin/reports" | "/dashboard/admin/settings" | "/dashboard/admin/students" | "/dashboard/admin/teachers" | "/dashboard/student" | "/dashboard/student/assignments" | "/dashboard/student/attendance" | "/dashboard/student/certificates" | "/dashboard/student/classes" | "/dashboard/student/courses" | "/dashboard/student/messages" | "/dashboard/student/profile" | "/dashboard/student/progress" | "/dashboard/student/tests" | "/dashboard/teacher" | "/dashboard/teacher/assignments" | "/dashboard/teacher/attendance" | "/dashboard/teacher/classes" | "/dashboard/teacher/content" | "/dashboard/teacher/grading" | "/dashboard/teacher/messages" | "/dashboard/teacher/profile" | "/dashboard/teacher/students" | "/forgot-password" | "/login" | "/register" | "/reset-password"
type AppRouteHandlerRoutes = "/api/admin/create-student" | "/api/admin/create-teacher" | "/api/college/join" | "/api/demo-request" | "/api/send-payment-email" | "/api/settings"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/create-student": {}
  "/api/admin/create-teacher": {}
  "/api/college/join": {}
  "/api/demo-request": {}
  "/api/send-payment-email": {}
  "/api/settings": {}
  "/dashboard/admin": {}
  "/dashboard/admin/attendance": {}
  "/dashboard/admin/batches": {}
  "/dashboard/admin/colleges": {}
  "/dashboard/admin/courses": {}
  "/dashboard/admin/crm": {}
  "/dashboard/admin/finance": {}
  "/dashboard/admin/reports": {}
  "/dashboard/admin/settings": {}
  "/dashboard/admin/students": {}
  "/dashboard/admin/teachers": {}
  "/dashboard/student": {}
  "/dashboard/student/assignments": {}
  "/dashboard/student/attendance": {}
  "/dashboard/student/certificates": {}
  "/dashboard/student/classes": {}
  "/dashboard/student/courses": {}
  "/dashboard/student/messages": {}
  "/dashboard/student/profile": {}
  "/dashboard/student/progress": {}
  "/dashboard/student/tests": {}
  "/dashboard/teacher": {}
  "/dashboard/teacher/assignments": {}
  "/dashboard/teacher/attendance": {}
  "/dashboard/teacher/classes": {}
  "/dashboard/teacher/content": {}
  "/dashboard/teacher/grading": {}
  "/dashboard/teacher/messages": {}
  "/dashboard/teacher/profile": {}
  "/dashboard/teacher/students": {}
  "/forgot-password": {}
  "/login": {}
  "/register": {}
  "/reset-password": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
