// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/dashboard/admin/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/batches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/batches">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/batches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/colleges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/colleges">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/colleges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/courses">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/crm">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/finance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/students">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/teachers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/teachers">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/teachers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/assignments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/certificates">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/classes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/courses">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/progress">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/student/tests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/student/tests">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/student/tests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/assignments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/classes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/content">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/grading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/grading">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/grading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/teacher/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/teacher/students">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/teacher/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/create-student/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-student">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/create-student/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/create-teacher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-teacher">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/create-teacher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/college/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/college/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/college/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/demo-request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo-request">> = Specific
  const handler = {} as typeof import("../../src/app/api/demo-request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/send-payment-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-payment-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/send-payment-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
